baseURL = "https://test-wantit.gcreate.jp/"
languageCode = "jp"
title = "だって欲しかったんだもん"
theme = "aether"
googleAnalytics = "UA-43849068-1"

hasCJKLanguage = true
paginate = 10
disqusShortname = ""
copyright = ""

[params]
    images = ["images/screenshot.jpg"]
    bgimg = "images/screenshot.jpg"
    rssFullContent = false
    homeFullContent = false
    archive-paginate = 3
    dateFormat = "2006/01/02"
    googleAutoAd = true

[sitemap]
    changefreq = "weekly"
    priority = 0.5
    filename = "sitemap.xml"

[author]
    name = "gen0083"

[social]
    twitter = "gen0083"
    github = "gen0083"

[permalinks]
    wp = "/:slug/"
    post = "/:slug/"

[blackfriday]
    extensions = ["hardLineBreak"]

# Related contents

[related]
    threshold = 70
    includeNewer = true
    toLower = false

[[related.indices]]
    name = "tags"
    weight = 100

[[related.indices]]
    name = "date"
    weight = 10