baseURL = "https://wantit.gcreate.jp/"
languageCode = "ja"
title = "イイモノ"
theme = "aether"
googleAnalytics = "UA-43849068-1"
hasCJKLanguage = true
paginate = 10
rssLimit = 10
summaryLength = 200

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[params]
    description = "パソコン、PC周辺機器、カメラ、自転車、コーヒー、本、ライフハック術など、私が日々生活する中で買ったもの、使ってみたものを記録し紹介するブログです。興味をもった理由を絡めて、実際の使い心地をレポートしていきます。"
    images = ["images/screenshot.jpg"]
    bgimg = "images/screenshot.jpg"
    rssFullContent = false
    homeFullContent = false
    archive-paginate = 3
    dateFormat = "2006/01/02"
    googleAutoAd = true
    githubBaseUrl = "https://github.com/gen0083/blog_wantit.gcreate.jp/tree/master/content/"

[frontmatter]
date = ["date","publishDate", ":fileModTime"]
lastmod = ["lastmod", ":fileModTime", "date"]

[sitemap]
    changefreq = "weekly"
    priority = 0.5
    filename = "sitemap.xml"

[outputFormats]
  [outputFormats.RSS]
    baseName = "rss"

[author]
    name = "gen0083"
    email = "archiherewego@gmail.com"

[social]
    twitter = "gen0083"
    github = "gen0083"

[permalinks]
    post = "/:slug/"
    forsite = "/forsite/:filename/"

[blackfriday]
    extensions = ["hardLineBreak"]

# Related contents

[related]
    threshold = 70
    includeNewer = true
    toLower = false

[[related.indices]]
    name = "tags"
    weight = 100

[[related.indices]]
    name = "date"
    weight = 10