baseURL = "https://test-wantit.gcreate.jp/"
languageCode = "ja"
title = "イイモノ"
theme = "aether"
googleAnalytics = "UA-43849068-1"

hasCJKLanguage = true
paginate = 10
disqusShortname = ""
copyright = ""

[params]
    description = "パソコン、PC周辺機器、カメラ、自転車、コーヒー、本、ライフハック術など、私が日々生活する中で買ったもの、使ってみたものを記録し紹介するブログです。興味をもった理由を絡めて、実際の使い心地をレポートしていきます。"
    images = ["images/screenshot.jpg"]
    bgimg = "images/screenshot.jpg"
    rssFullContent = false
    homeFullContent = false
    archive-paginate = 3
    dateFormat = "2006/01/02"
    googleAutoAd = true

[frontmatter]
date = ["date","publishDate", ":fileModTime"]
lastmod = ["lastmod", ":fileModTime", "date"]

[sitemap]
    changefreq = "weekly"
    priority = 0.5
    filename = "sitemap.xml"

[author]
    name = "gen0083"

[social]
    twitter = "gen0083"
    github = "gen0083"

[permalinks]
    post = "/:slug/"
    forsite = "/forsite/:filename/"

[blackfriday]
    extensions = ["hardLineBreak"]

# Related contents

[related]
    threshold = 70
    includeNewer = true
    toLower = false

[[related.indices]]
    name = "tags"
    weight = 100

[[related.indices]]
    name = "date"
    weight = 10