version: 2.1

orbs:
  hugo: circleci/hugo@0.4.1
workflows:
  main:
    jobs:
      - hugo/build:
          html-proofer: true
          version: '0.62.2'
      - test1:
          name: check slug duplication
          command: ./scripts/check_slug_duplicate.sh
          requires:
            - hugo/build
      - test2:
          name: textlint check
          command: npx textlint content/**/**/*.md
          requires:
            - hugo/build