version: 2.1

jobs:
  build:
    working_directory: ~/project/{ORG_NAME}}/{{REPO_NAME}}
    docker:
      - image: cimg/go:1.19.2-node
    steps:
      - run:
          name: setup environment
          command: |
            sudo apt update
            sudo apt-get install hugo
            mkdir -p ~/bin/ && export export PATH="~/bin/:$PATH"
            curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s -- -b ~/bin && chmod +x ~/bin/reviewdog
      - checkout
      - run:
          name: sync submodule
          command: |
            git submodule sync
            git submodule update --init
      - restore_cache:
          keys:
            - node_modules-cache-{{ checksum "package-lock.json" }}
      - run: npm i
      - save_cache:
          key: node_modules-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules/
      - run:
          name: check slug duplication
          command: ./scripts/check_slug_duplicate.sh
      - run:
          name: textlint check
          command: npx textlint content/**/**/*.md
      - run:
          name: textlint on github
          command: npx textlint -f checkstyle content/**/**/*.md | reviewdog -f=checkstyle -name="textlint" -reporter=github-pr-review -diff="git diff FETCH_HEAD"
          when: on_fail